/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FYIApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FYIApiTests
    {
        private FYIApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FYIApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FYIApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FYIApi
            //Assert.IsInstanceOfType(typeof(FYIApi), instance, "instance is a FYIApi");
        }

        
        /// <summary>
        /// Test FyiDeliveryoptionsDeviceIdDelete
        /// </summary>
        [Test]
        public void FyiDeliveryoptionsDeviceIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deviceId = null;
            //var response = instance.FyiDeliveryoptionsDeviceIdDelete(deviceId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test FyiDeliveryoptionsDevicePost
        /// </summary>
        [Test]
        public void FyiDeliveryoptionsDevicePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Body body = null;
            //var response = instance.FyiDeliveryoptionsDevicePost(body);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test FyiDeliveryoptionsEmailPut
        /// </summary>
        [Test]
        public void FyiDeliveryoptionsEmailPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string enabled = null;
            //var response = instance.FyiDeliveryoptionsEmailPut(enabled);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test FyiDeliveryoptionsGet
        /// </summary>
        [Test]
        public void FyiDeliveryoptionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FyiDeliveryoptionsGet();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test FyiDisclaimerTypecodeGet
        /// </summary>
        [Test]
        public void FyiDisclaimerTypecodeGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string typecode = null;
            //var response = instance.FyiDisclaimerTypecodeGet(typecode);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test FyiDisclaimerTypecodePut
        /// </summary>
        [Test]
        public void FyiDisclaimerTypecodePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string typecode = null;
            //var response = instance.FyiDisclaimerTypecodePut(typecode);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test FyiNotificationsGet
        /// </summary>
        [Test]
        public void FyiNotificationsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string max = null;
            //string exclude = null;
            //string include = null;
            //var response = instance.FyiNotificationsGet(max, exclude, include);
            //Assert.IsInstanceOf<Notifications> (response, "response is Notifications");
        }
        
        /// <summary>
        /// Test FyiNotificationsMoreGet
        /// </summary>
        [Test]
        public void FyiNotificationsMoreGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.FyiNotificationsMoreGet(id);
            //Assert.IsInstanceOf<Notifications> (response, "response is Notifications");
        }
        
        /// <summary>
        /// Test FyiNotificationsNotificationIdPut
        /// </summary>
        [Test]
        public void FyiNotificationsNotificationIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string notificationId = null;
            //var response = instance.FyiNotificationsNotificationIdPut(notificationId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test FyiSettingsGet
        /// </summary>
        [Test]
        public void FyiSettingsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FyiSettingsGet();
            //Assert.IsInstanceOf<List<Object>> (response, "response is List<Object>");
        }
        
        /// <summary>
        /// Test FyiSettingsTypecodePost
        /// </summary>
        [Test]
        public void FyiSettingsTypecodePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string typecode = null;
            //Body body = null;
            //var response = instance.FyiSettingsTypecodePost(typecode, body);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test FyiUnreadnumberGet
        /// </summary>
        [Test]
        public void FyiUnreadnumberGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.FyiUnreadnumberGet();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
