/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PnLApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PnLApiTests
    {
        private PnLApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PnLApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PnLApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PnLApi
            //Assert.IsInstanceOfType(typeof(PnLApi), instance, "instance is a PnLApi");
        }

        
        /// <summary>
        /// Test IserverAccountPnlPartitionedGet
        /// </summary>
        [Test]
        public void IserverAccountPnlPartitionedGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.IserverAccountPnlPartitionedGet();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
