/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScannerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ScannerApiTests
    {
        private ScannerApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ScannerApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScannerApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ScannerApi
            //Assert.IsInstanceOfType(typeof(ScannerApi), instance, "instance is a ScannerApi");
        }

        
        /// <summary>
        /// Test IserverScannerParamsGet
        /// </summary>
        [Test]
        public void IserverScannerParamsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.IserverScannerParamsGet();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test IserverScannerRunPost
        /// </summary>
        [Test]
        public void IserverScannerRunPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ScannerParams body = null;
            //var response = instance.IserverScannerRunPost(body);
            //Assert.IsInstanceOf<List<Object>> (response, "response is List<Object>");
        }
        
    }

}
