/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SetAccount
    /// </summary>
    [DataContract]
    public partial class SetAccount :  IEquatable<SetAccount>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetAccount" /> class.
        /// </summary>
        /// <param name="acctId">Account ID.</param>
        public SetAccount(string acctId = default(string))
        {
            this.AcctId = acctId;
        }
        
        /// <summary>
        /// Account ID
        /// </summary>
        /// <value>Account ID</value>
        [DataMember(Name="acctId", EmitDefaultValue=false)]
        public string AcctId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SetAccount {\n");
            sb.Append("  AcctId: ").Append(AcctId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetAccount);
        }

        /// <summary>
        /// Returns true if SetAccount instances are equal
        /// </summary>
        /// <param name="input">Instance of SetAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetAccount input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AcctId == input.AcctId ||
                    (this.AcctId != null &&
                    this.AcctId.Equals(input.AcctId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AcctId != null)
                    hashCode = hashCode * 59 + this.AcctId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
