/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountTests
    {
        // TODO uncomment below to declare an instance variable for Account
        //private Account instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Account
            //instance = new Account();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Test]
        public void AccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Account
            //Assert.IsInstanceOfType<Account> (instance, "variable 'instance' is a Account");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'AccountVan'
        /// </summary>
        [Test]
        public void AccountVanTest()
        {
            // TODO unit test for the property 'AccountVan'
        }
        /// <summary>
        /// Test the property 'AccountTitle'
        /// </summary>
        [Test]
        public void AccountTitleTest()
        {
            // TODO unit test for the property 'AccountTitle'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'AccountAlias'
        /// </summary>
        [Test]
        public void AccountAliasTest()
        {
            // TODO unit test for the property 'AccountAlias'
        }
        /// <summary>
        /// Test the property 'AccountStatus'
        /// </summary>
        [Test]
        public void AccountStatusTest()
        {
            // TODO unit test for the property 'AccountStatus'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TradingType'
        /// </summary>
        [Test]
        public void TradingTypeTest()
        {
            // TODO unit test for the property 'TradingType'
        }
        /// <summary>
        /// Test the property 'Faclient'
        /// </summary>
        [Test]
        public void FaclientTest()
        {
            // TODO unit test for the property 'Faclient'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Test]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'Desc'
        /// </summary>
        [Test]
        public void DescTest()
        {
            // TODO unit test for the property 'Desc'
        }
        /// <summary>
        /// Test the property 'Covestor'
        /// </summary>
        [Test]
        public void CovestorTest()
        {
            // TODO unit test for the property 'Covestor'
        }
        /// <summary>
        /// Test the property 'Master'
        /// </summary>
        [Test]
        public void MasterTest()
        {
            // TODO unit test for the property 'Master'
        }

    }

}
