/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AlertResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertResponseTests
    {
        // TODO uncomment below to declare an instance variable for AlertResponse
        //private AlertResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertResponse
            //instance = new AlertResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertResponse
        /// </summary>
        [Test]
        public void AlertResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertResponse
            //Assert.IsInstanceOfType<AlertResponse> (instance, "variable 'instance' is a AlertResponse");
        }


        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Test]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'AlertName'
        /// </summary>
        [Test]
        public void AlertNameTest()
        {
            // TODO unit test for the property 'AlertName'
        }
        /// <summary>
        /// Test the property 'AlertMessage'
        /// </summary>
        [Test]
        public void AlertMessageTest()
        {
            // TODO unit test for the property 'AlertMessage'
        }
        /// <summary>
        /// Test the property 'AlertActive'
        /// </summary>
        [Test]
        public void AlertActiveTest()
        {
            // TODO unit test for the property 'AlertActive'
        }
        /// <summary>
        /// Test the property 'AlertRepeatable'
        /// </summary>
        [Test]
        public void AlertRepeatableTest()
        {
            // TODO unit test for the property 'AlertRepeatable'
        }
        /// <summary>
        /// Test the property 'AlertEmail'
        /// </summary>
        [Test]
        public void AlertEmailTest()
        {
            // TODO unit test for the property 'AlertEmail'
        }
        /// <summary>
        /// Test the property 'AlertSendMessage'
        /// </summary>
        [Test]
        public void AlertSendMessageTest()
        {
            // TODO unit test for the property 'AlertSendMessage'
        }
        /// <summary>
        /// Test the property 'Tif'
        /// </summary>
        [Test]
        public void TifTest()
        {
            // TODO unit test for the property 'Tif'
        }
        /// <summary>
        /// Test the property 'ExpireTime'
        /// </summary>
        [Test]
        public void ExpireTimeTest()
        {
            // TODO unit test for the property 'ExpireTime'
        }
        /// <summary>
        /// Test the property 'OrderStatus'
        /// </summary>
        [Test]
        public void OrderStatusTest()
        {
            // TODO unit test for the property 'OrderStatus'
        }
        /// <summary>
        /// Test the property 'OutsideRth'
        /// </summary>
        [Test]
        public void OutsideRthTest()
        {
            // TODO unit test for the property 'OutsideRth'
        }
        /// <summary>
        /// Test the property 'ItwsOrdersOnly'
        /// </summary>
        [Test]
        public void ItwsOrdersOnlyTest()
        {
            // TODO unit test for the property 'ItwsOrdersOnly'
        }
        /// <summary>
        /// Test the property 'AlertShowPopup'
        /// </summary>
        [Test]
        public void AlertShowPopupTest()
        {
            // TODO unit test for the property 'AlertShowPopup'
        }
        /// <summary>
        /// Test the property 'AlertTriggered'
        /// </summary>
        [Test]
        public void AlertTriggeredTest()
        {
            // TODO unit test for the property 'AlertTriggered'
        }
        /// <summary>
        /// Test the property 'OrderNotEditable'
        /// </summary>
        [Test]
        public void OrderNotEditableTest()
        {
            // TODO unit test for the property 'OrderNotEditable'
        }
        /// <summary>
        /// Test the property 'ToolId'
        /// </summary>
        [Test]
        public void ToolIdTest()
        {
            // TODO unit test for the property 'ToolId'
        }
        /// <summary>
        /// Test the property 'AlertPlayAudio'
        /// </summary>
        [Test]
        public void AlertPlayAudioTest()
        {
            // TODO unit test for the property 'AlertPlayAudio'
        }
        /// <summary>
        /// Test the property 'AlertMtaCurrency'
        /// </summary>
        [Test]
        public void AlertMtaCurrencyTest()
        {
            // TODO unit test for the property 'AlertMtaCurrency'
        }
        /// <summary>
        /// Test the property 'AlertMtaDefaults'
        /// </summary>
        [Test]
        public void AlertMtaDefaultsTest()
        {
            // TODO unit test for the property 'AlertMtaDefaults'
        }
        /// <summary>
        /// Test the property 'TimeZone'
        /// </summary>
        [Test]
        public void TimeZoneTest()
        {
            // TODO unit test for the property 'TimeZone'
        }
        /// <summary>
        /// Test the property 'AlertDefaultType'
        /// </summary>
        [Test]
        public void AlertDefaultTypeTest()
        {
            // TODO unit test for the property 'AlertDefaultType'
        }
        /// <summary>
        /// Test the property 'ConditionSize'
        /// </summary>
        [Test]
        public void ConditionSizeTest()
        {
            // TODO unit test for the property 'ConditionSize'
        }
        /// <summary>
        /// Test the property 'ConditionOutsideRth'
        /// </summary>
        [Test]
        public void ConditionOutsideRthTest()
        {
            // TODO unit test for the property 'ConditionOutsideRth'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Test]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }

    }

}
