/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AlertRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertRequestTests
    {
        // TODO uncomment below to declare an instance variable for AlertRequest
        //private AlertRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertRequest
            //instance = new AlertRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertRequest
        /// </summary>
        [Test]
        public void AlertRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertRequest
            //Assert.IsInstanceOfType<AlertRequest> (instance, "variable 'instance' is a AlertRequest");
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'AlertName'
        /// </summary>
        [Test]
        public void AlertNameTest()
        {
            // TODO unit test for the property 'AlertName'
        }
        /// <summary>
        /// Test the property 'AlertMessage'
        /// </summary>
        [Test]
        public void AlertMessageTest()
        {
            // TODO unit test for the property 'AlertMessage'
        }
        /// <summary>
        /// Test the property 'AlertRepeatable'
        /// </summary>
        [Test]
        public void AlertRepeatableTest()
        {
            // TODO unit test for the property 'AlertRepeatable'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'SendMessage'
        /// </summary>
        [Test]
        public void SendMessageTest()
        {
            // TODO unit test for the property 'SendMessage'
        }
        /// <summary>
        /// Test the property 'Tif'
        /// </summary>
        [Test]
        public void TifTest()
        {
            // TODO unit test for the property 'Tif'
        }
        /// <summary>
        /// Test the property 'ExpireTime'
        /// </summary>
        [Test]
        public void ExpireTimeTest()
        {
            // TODO unit test for the property 'ExpireTime'
        }
        /// <summary>
        /// Test the property 'OutsideRth'
        /// </summary>
        [Test]
        public void OutsideRthTest()
        {
            // TODO unit test for the property 'OutsideRth'
        }
        /// <summary>
        /// Test the property 'ITWSOrdersOnly'
        /// </summary>
        [Test]
        public void ITWSOrdersOnlyTest()
        {
            // TODO unit test for the property 'ITWSOrdersOnly'
        }
        /// <summary>
        /// Test the property 'ShowPopup'
        /// </summary>
        [Test]
        public void ShowPopupTest()
        {
            // TODO unit test for the property 'ShowPopup'
        }
        /// <summary>
        /// Test the property 'ToolId'
        /// </summary>
        [Test]
        public void ToolIdTest()
        {
            // TODO unit test for the property 'ToolId'
        }
        /// <summary>
        /// Test the property 'PlayAudio'
        /// </summary>
        [Test]
        public void PlayAudioTest()
        {
            // TODO unit test for the property 'PlayAudio'
        }
        /// <summary>
        /// Test the property 'Conditions'
        /// </summary>
        [Test]
        public void ConditionsTest()
        {
            // TODO unit test for the property 'Conditions'
        }

    }

}
