/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MarketData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarketDataTests
    {
        // TODO uncomment below to declare an instance variable for MarketData
        //private MarketData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarketData
            //instance = new MarketData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarketData
        /// </summary>
        [Test]
        public void MarketDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarketData
            //Assert.IsInstanceOfType<MarketData> (instance, "variable 'instance' is a MarketData");
        }


        /// <summary>
        /// Test the property 'Conid'
        /// </summary>
        [Test]
        public void ConidTest()
        {
            // TODO unit test for the property 'Conid'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Test]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'MinTick'
        /// </summary>
        [Test]
        public void MinTickTest()
        {
            // TODO unit test for the property 'MinTick'
        }
        /// <summary>
        /// Test the property 'Last'
        /// </summary>
        [Test]
        public void LastTest()
        {
            // TODO unit test for the property 'Last'
        }
        /// <summary>
        /// Test the property 'LastSize'
        /// </summary>
        [Test]
        public void LastSizeTest()
        {
            // TODO unit test for the property 'LastSize'
        }
        /// <summary>
        /// Test the property 'Bid'
        /// </summary>
        [Test]
        public void BidTest()
        {
            // TODO unit test for the property 'Bid'
        }
        /// <summary>
        /// Test the property 'BidSize'
        /// </summary>
        [Test]
        public void BidSizeTest()
        {
            // TODO unit test for the property 'BidSize'
        }
        /// <summary>
        /// Test the property 'Ask'
        /// </summary>
        [Test]
        public void AskTest()
        {
            // TODO unit test for the property 'Ask'
        }
        /// <summary>
        /// Test the property 'AskSize'
        /// </summary>
        [Test]
        public void AskSizeTest()
        {
            // TODO unit test for the property 'AskSize'
        }

    }

}
