/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModifyOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModifyOrderTests
    {
        // TODO uncomment below to declare an instance variable for ModifyOrder
        //private ModifyOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModifyOrder
            //instance = new ModifyOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModifyOrder
        /// </summary>
        [Test]
        public void ModifyOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModifyOrder
            //Assert.IsInstanceOfType<ModifyOrder> (instance, "variable 'instance' is a ModifyOrder");
        }


        /// <summary>
        /// Test the property 'AcctId'
        /// </summary>
        [Test]
        public void AcctIdTest()
        {
            // TODO unit test for the property 'AcctId'
        }
        /// <summary>
        /// Test the property 'Conid'
        /// </summary>
        [Test]
        public void ConidTest()
        {
            // TODO unit test for the property 'Conid'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Test]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'OutsideRTH'
        /// </summary>
        [Test]
        public void OutsideRTHTest()
        {
            // TODO unit test for the property 'OutsideRTH'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'AuxPrice'
        /// </summary>
        [Test]
        public void AuxPriceTest()
        {
            // TODO unit test for the property 'AuxPrice'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Test]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'ListingExchange'
        /// </summary>
        [Test]
        public void ListingExchangeTest()
        {
            // TODO unit test for the property 'ListingExchange'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'Tif'
        /// </summary>
        [Test]
        public void TifTest()
        {
            // TODO unit test for the property 'Tif'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
