/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderRequestTests
    {
        // TODO uncomment below to declare an instance variable for OrderRequest
        //private OrderRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderRequest
            //instance = new OrderRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderRequest
        /// </summary>
        [Test]
        public void OrderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderRequest
            //Assert.IsInstanceOfType<OrderRequest> (instance, "variable 'instance' is a OrderRequest");
        }


        /// <summary>
        /// Test the property 'AcctId'
        /// </summary>
        [Test]
        public void AcctIdTest()
        {
            // TODO unit test for the property 'AcctId'
        }
        /// <summary>
        /// Test the property 'Conid'
        /// </summary>
        [Test]
        public void ConidTest()
        {
            // TODO unit test for the property 'Conid'
        }
        /// <summary>
        /// Test the property 'SecType'
        /// </summary>
        [Test]
        public void SecTypeTest()
        {
            // TODO unit test for the property 'SecType'
        }
        /// <summary>
        /// Test the property 'COID'
        /// </summary>
        [Test]
        public void COIDTest()
        {
            // TODO unit test for the property 'COID'
        }
        /// <summary>
        /// Test the property 'ParentId'
        /// </summary>
        [Test]
        public void ParentIdTest()
        {
            // TODO unit test for the property 'ParentId'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Test]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'ListingExchange'
        /// </summary>
        [Test]
        public void ListingExchangeTest()
        {
            // TODO unit test for the property 'ListingExchange'
        }
        /// <summary>
        /// Test the property 'OutsideRTH'
        /// </summary>
        [Test]
        public void OutsideRTHTest()
        {
            // TODO unit test for the property 'OutsideRTH'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Test]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Test]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }
        /// <summary>
        /// Test the property 'Tif'
        /// </summary>
        [Test]
        public void TifTest()
        {
            // TODO unit test for the property 'Tif'
        }
        /// <summary>
        /// Test the property 'Referrer'
        /// </summary>
        [Test]
        public void ReferrerTest()
        {
            // TODO unit test for the property 'Referrer'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'FxQty'
        /// </summary>
        [Test]
        public void FxQtyTest()
        {
            // TODO unit test for the property 'FxQty'
        }
        /// <summary>
        /// Test the property 'UseAdaptive'
        /// </summary>
        [Test]
        public void UseAdaptiveTest()
        {
            // TODO unit test for the property 'UseAdaptive'
        }
        /// <summary>
        /// Test the property 'IsCurrencyConversion'
        /// </summary>
        [Test]
        public void IsCurrencyConversionTest()
        {
            // TODO unit test for the property 'IsCurrencyConversion'
        }
        /// <summary>
        /// Test the property 'AllocationMethod'
        /// </summary>
        [Test]
        public void AllocationMethodTest()
        {
            // TODO unit test for the property 'AllocationMethod'
        }

    }

}
