/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Performance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PerformanceTests
    {
        // TODO uncomment below to declare an instance variable for Performance
        //private Performance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Performance
            //instance = new Performance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Performance
        /// </summary>
        [Test]
        public void PerformanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Performance
            //Assert.IsInstanceOfType<Performance> (instance, "variable 'instance' is a Performance");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Cps'
        /// </summary>
        [Test]
        public void CpsTest()
        {
            // TODO unit test for the property 'Cps'
        }
        /// <summary>
        /// Test the property 'Tpps'
        /// </summary>
        [Test]
        public void TppsTest()
        {
            // TODO unit test for the property 'Tpps'
        }
        /// <summary>
        /// Test the property 'Nav'
        /// </summary>
        [Test]
        public void NavTest()
        {
            // TODO unit test for the property 'Nav'
        }
        /// <summary>
        /// Test the property 'Pm'
        /// </summary>
        [Test]
        public void PmTest()
        {
            // TODO unit test for the property 'Pm'
        }
        /// <summary>
        /// Test the property 'Included'
        /// </summary>
        [Test]
        public void IncludedTest()
        {
            // TODO unit test for the property 'Included'
        }
        /// <summary>
        /// Test the property 'CurrencyType'
        /// </summary>
        [Test]
        public void CurrencyTypeTest()
        {
            // TODO unit test for the property 'CurrencyType'
        }
        /// <summary>
        /// Test the property 'Rc'
        /// </summary>
        [Test]
        public void RcTest()
        {
            // TODO unit test for the property 'Rc'
        }

    }

}
