/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ScannerParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScannerParamsTests
    {
        // TODO uncomment below to declare an instance variable for ScannerParams
        //private ScannerParams instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScannerParams
            //instance = new ScannerParams();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScannerParams
        /// </summary>
        [Test]
        public void ScannerParamsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScannerParams
            //Assert.IsInstanceOfType<ScannerParams> (instance, "variable 'instance' is a ScannerParams");
        }


        /// <summary>
        /// Test the property 'InstrumentList'
        /// </summary>
        [Test]
        public void InstrumentListTest()
        {
            // TODO unit test for the property 'InstrumentList'
        }
        /// <summary>
        /// Test the property 'LocationTree'
        /// </summary>
        [Test]
        public void LocationTreeTest()
        {
            // TODO unit test for the property 'LocationTree'
        }
        /// <summary>
        /// Test the property 'FilterList'
        /// </summary>
        [Test]
        public void FilterListTest()
        {
            // TODO unit test for the property 'FilterList'
        }
        /// <summary>
        /// Test the property 'ScanTypeList'
        /// </summary>
        [Test]
        public void ScanTypeListTest()
        {
            // TODO unit test for the property 'ScanTypeList'
        }

    }

}
