/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SecdefInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SecdefInfoTests
    {
        // TODO uncomment below to declare an instance variable for SecdefInfo
        //private SecdefInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SecdefInfo
            //instance = new SecdefInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SecdefInfo
        /// </summary>
        [Test]
        public void SecdefInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SecdefInfo
            //Assert.IsInstanceOfType<SecdefInfo> (instance, "variable 'instance' is a SecdefInfo");
        }


        /// <summary>
        /// Test the property 'Conid'
        /// </summary>
        [Test]
        public void ConidTest()
        {
            // TODO unit test for the property 'Conid'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'SecType'
        /// </summary>
        [Test]
        public void SecTypeTest()
        {
            // TODO unit test for the property 'SecType'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Test]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'ListingExchange'
        /// </summary>
        [Test]
        public void ListingExchangeTest()
        {
            // TODO unit test for the property 'ListingExchange'
        }
        /// <summary>
        /// Test the property 'Right'
        /// </summary>
        [Test]
        public void RightTest()
        {
            // TODO unit test for the property 'Right'
        }
        /// <summary>
        /// Test the property 'Strike'
        /// </summary>
        [Test]
        public void StrikeTest()
        {
            // TODO unit test for the property 'Strike'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Cusip'
        /// </summary>
        [Test]
        public void CusipTest()
        {
            // TODO unit test for the property 'Cusip'
        }
        /// <summary>
        /// Test the property 'Coupon'
        /// </summary>
        [Test]
        public void CouponTest()
        {
            // TODO unit test for the property 'Coupon'
        }
        /// <summary>
        /// Test the property 'Desc1'
        /// </summary>
        [Test]
        public void Desc1Test()
        {
            // TODO unit test for the property 'Desc1'
        }
        /// <summary>
        /// Test the property 'Desc2'
        /// </summary>
        [Test]
        public void Desc2Test()
        {
            // TODO unit test for the property 'Desc2'
        }
        /// <summary>
        /// Test the property 'MaturityDate'
        /// </summary>
        [Test]
        public void MaturityDateTest()
        {
            // TODO unit test for the property 'MaturityDate'
        }
        /// <summary>
        /// Test the property 'Multiplier'
        /// </summary>
        [Test]
        public void MultiplierTest()
        {
            // TODO unit test for the property 'Multiplier'
        }
        /// <summary>
        /// Test the property 'TradingClass'
        /// </summary>
        [Test]
        public void TradingClassTest()
        {
            // TODO unit test for the property 'TradingClass'
        }
        /// <summary>
        /// Test the property 'ValidExchanges'
        /// </summary>
        [Test]
        public void ValidExchangesTest()
        {
            // TODO unit test for the property 'ValidExchanges'
        }

    }

}
