/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SetAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SetAccountTests
    {
        // TODO uncomment below to declare an instance variable for SetAccount
        //private SetAccount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SetAccount
            //instance = new SetAccount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SetAccount
        /// </summary>
        [Test]
        public void SetAccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SetAccount
            //Assert.IsInstanceOfType<SetAccount> (instance, "variable 'instance' is a SetAccount");
        }


        /// <summary>
        /// Test the property 'AcctId'
        /// </summary>
        [Test]
        public void AcctIdTest()
        {
            // TODO unit test for the property 'AcctId'
        }

    }

}
