/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StatsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatsDataTests
    {
        // TODO uncomment below to declare an instance variable for StatsData
        //private StatsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StatsData
            //instance = new StatsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatsData
        /// </summary>
        [Test]
        public void StatsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StatsData
            //Assert.IsInstanceOfType<StatsData> (instance, "variable 'instance' is a StatsData");
        }


        /// <summary>
        /// Test the property 'Conid'
        /// </summary>
        [Test]
        public void ConidTest()
        {
            // TODO unit test for the property 'Conid'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Test]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'V'
        /// </summary>
        [Test]
        public void VTest()
        {
            // TODO unit test for the property 'V'
        }
        /// <summary>
        /// Test the property 'T'
        /// </summary>
        [Test]
        public void TTest()
        {
            // TODO unit test for the property 'T'
        }
        /// <summary>
        /// Test the property 'TT'
        /// </summary>
        [Test]
        public void TTTest()
        {
            // TODO unit test for the property 'TT'
        }
        /// <summary>
        /// Test the property 'P'
        /// </summary>
        [Test]
        public void PTest()
        {
            // TODO unit test for the property 'P'
        }

    }

}
