/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Summary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummaryTests
    {
        // TODO uncomment below to declare an instance variable for Summary
        //private Summary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Summary
            //instance = new Summary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Summary
        /// </summary>
        [Test]
        public void SummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Summary
            //Assert.IsInstanceOfType<Summary> (instance, "variable 'instance' is a Summary");
        }


        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'ExcludedAccounts'
        /// </summary>
        [Test]
        public void ExcludedAccountsTest()
        {
            // TODO unit test for the property 'ExcludedAccounts'
        }
        /// <summary>
        /// Test the property 'LastSuccessfulUpdate'
        /// </summary>
        [Test]
        public void LastSuccessfulUpdateTest()
        {
            // TODO unit test for the property 'LastSuccessfulUpdate'
        }
        /// <summary>
        /// Test the property 'AccountSummaries'
        /// </summary>
        [Test]
        public void AccountSummariesTest()
        {
            // TODO unit test for the property 'AccountSummaries'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'HasExternalAccounts'
        /// </summary>
        [Test]
        public void HasExternalAccountsTest()
        {
            // TODO unit test for the property 'HasExternalAccounts'
        }
        /// <summary>
        /// Test the property 'Rc'
        /// </summary>
        [Test]
        public void RcTest()
        {
            // TODO unit test for the property 'Rc'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Pm'
        /// </summary>
        [Test]
        public void PmTest()
        {
            // TODO unit test for the property 'Pm'
        }
        /// <summary>
        /// Test the property 'View'
        /// </summary>
        [Test]
        public void ViewTest()
        {
            // TODO unit test for the property 'View'
        }
        /// <summary>
        /// Test the property 'BalanceByDate'
        /// </summary>
        [Test]
        public void BalanceByDateTest()
        {
            // TODO unit test for the property 'BalanceByDate'
        }

    }

}
