/* 
 * Client Portal Web API
 *
 * Client Portal Web API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Trade
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TradeTests
    {
        // TODO uncomment below to declare an instance variable for Trade
        //private Trade instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Trade
            //instance = new Trade();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Trade
        /// </summary>
        [Test]
        public void TradeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Trade
            //Assert.IsInstanceOfType<Trade> (instance, "variable 'instance' is a Trade");
        }


        /// <summary>
        /// Test the property 'ExecutionId'
        /// </summary>
        [Test]
        public void ExecutionIdTest()
        {
            // TODO unit test for the property 'ExecutionId'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Test]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'OrderDescription'
        /// </summary>
        [Test]
        public void OrderDescriptionTest()
        {
            // TODO unit test for the property 'OrderDescription'
        }
        /// <summary>
        /// Test the property 'TradeTime'
        /// </summary>
        [Test]
        public void TradeTimeTest()
        {
            // TODO unit test for the property 'TradeTime'
        }
        /// <summary>
        /// Test the property 'TradeTimeR'
        /// </summary>
        [Test]
        public void TradeTimeRTest()
        {
            // TODO unit test for the property 'TradeTimeR'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Submitter'
        /// </summary>
        [Test]
        public void SubmitterTest()
        {
            // TODO unit test for the property 'Submitter'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Test]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'Comission'
        /// </summary>
        [Test]
        public void ComissionTest()
        {
            // TODO unit test for the property 'Comission'
        }
        /// <summary>
        /// Test the property 'NetAmount'
        /// </summary>
        [Test]
        public void NetAmountTest()
        {
            // TODO unit test for the property 'NetAmount'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Test]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'ContractDescription1'
        /// </summary>
        [Test]
        public void ContractDescription1Test()
        {
            // TODO unit test for the property 'ContractDescription1'
        }
        /// <summary>
        /// Test the property 'SecType'
        /// </summary>
        [Test]
        public void SecTypeTest()
        {
            // TODO unit test for the property 'SecType'
        }
        /// <summary>
        /// Test the property 'Conidex'
        /// </summary>
        [Test]
        public void ConidexTest()
        {
            // TODO unit test for the property 'Conidex'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'ClearingId'
        /// </summary>
        [Test]
        public void ClearingIdTest()
        {
            // TODO unit test for the property 'ClearingId'
        }
        /// <summary>
        /// Test the property 'ClearingName'
        /// </summary>
        [Test]
        public void ClearingNameTest()
        {
            // TODO unit test for the property 'ClearingName'
        }
        /// <summary>
        /// Test the property 'OrderRef'
        /// </summary>
        [Test]
        public void OrderRefTest()
        {
            // TODO unit test for the property 'OrderRef'
        }

    }

}
